spring:
  application:
    name: Job-Posting-Application

  datasource:
    url: jdbc:postgresql://localhost:5432/jobdemo
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver



#  security:
#    user:
#      name: user
#      password: 1234

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: redis
    cache-names: job
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    layout: StandaloneLayout
    syntax-highlight:
      theme: material
    path: /swagger-ui.html
    deep-linking: true
    tags-sorter: alpha
    operations-sorter: method


#admin:
#  password: admin@123
#user:
#  password: user@123

jwt:
  secret: 8b06ee5f2759bcf766c55862e9b32a0a8e9d4490b236b53108ca2c9cbfea9278
  expiration: 3600000








